# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download": "base.ipynb",
         "unzip": "base.ipynb",
         "AbstractDataset": "base.ipynb",
         "AbstractDatasetv2": "base.ipynb",
         "Synthetic": "synthetic.ipynb",
         "Session": "synthetic.ipynb",
         "SequentialMarkov": "synthetic.ipynb",
         "BetaBandit": "bandits.ipynb",
         "EpsilonBandit": "bandits.ipynb",
         "Multi_Layer_Perceptron": "dnn.ipynb",
         "CollabFNet": "dnn.ipynb",
         "EmbeddingNet": "embedding.ipynb",
         "get_list": "embedding.ipynb",
         "EpsilonGreedy": "epsilon.ipynb",
         "EpsilonGreedyRunner": "epsilon.ipynb",
         "MF": "factorization.ipynb",
         "BiasedMF": "factorization.ipynb",
         "NeuMF": "factorization.ipynb",
         "GMF": "factorization.ipynb",
         "seed_everything": "utils.ipynb",
         "simple_aggregate": "aggregate.ipynb",
         "label_encode": "encode.ipynb",
         "simple_normalize": "normalize.ipynb",
         "simple_negative_sampling": "sampling.ipynb",
         "AbstractNegativeSampler": "sampling.ipynb",
         "RandomNegativeSampler": "sampling.ipynb",
         "PopularNegativeSampler": "sampling.ipynb",
         "Configurator": "config.ipynb",
         "set_logger": "logging.ipynb"}

modules = ["datasets/base.py",
           "datasets/synthetic.py",
           "models/bandits.py",
           "models/dnn.py",
           "models/embedding.py",
           "models/epsilon.py",
           "models/factorization.py",
           "pytorch/utils.py",
           "transforms/aggregate.py",
           "transforms/encode.py",
           "transforms/normalize.py",
           "transforms/sampling.py",
           "utils/config.py",
           "utils/logging.py"]

doc_url = "https://RecoHut-Projects.github.io/recohut/"

git_url = "https://github.com/RecoHut-Projects/recohut/tree/master/"

def custom_doc_links(name): return None
