# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DeepMF": "deepmf.ipynb",
         "NCF": "ncf.ipynb",
         "VDeepMF": "vdeepmf.ipynb",
         "VNCF": "vncf.ipynb",
         "seed_everything": "utils.ipynb",
         "Configurator": "config.ipynb",
         "set_logger": "logging.ipynb"}

modules = ["models/tensorflow/deepmf.py",
           "models/tensorflow/ncf.py",
           "models/tensorflow/vdeepmf.py",
           "models/tensorflow/vncf.py",
           "pytorch/utils.py",
           "utils/config.py",
           "utils/logging.py"]

doc_url = "https://RecoHut-Projects.github.io/recohut/"

git_url = "https://github.com/RecoHut-Projects/recohut/tree/master/"

def custom_doc_links(name): return None
