# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Configurator": "config.ipynb",
         "set_logger": "logging.ipynb"}

modules = ["utils/config.py",
           "utils/logging.py"]

doc_url = "https://RecoHut-Projects.github.io/recohut/"

git_url = "https://github.com/RecoHut-Projects/recohut/tree/master/"

def custom_doc_links(name): return None
