# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils/utils.datetime.ipynb (unless otherwise specified).

__all__ = ['convert_to_unix']

# Cell
import pandas as pd

# Cell
def convert_to_unix(s: pd.Series):
    return (s - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')